"""The world layer: closed manifests, the rules store, and pure derivation.

Slice 1's registry lives in `science.world.registry`, slice 2's rules store in
`science.world.rules`, its epoch carrier and publication in
`science.world.epoch`, its pure derivations in `science.world.derive` and its
read surface in `science.world.read`; this module is the package's import
surface and re-exports them unchanged. The private names below are the seams
`science.root`, `science.corpus`, and the suite already reach for through
`science.world`, kept importable so the promotion moves no caller. Anything
that *replaces* one of them — a monkeypatched global — must patch the module
where the binding the implementation reads lives.
"""

from __future__ import annotations

from science.world.derive import (
    BELIEF_INPUT_KIND,
    CERTIFICATION_INVENTORY_DOMAIN,
    COREFERENCE_MAP_DOMAIN,
    PRODUCER_SNAPSHOT_DOMAIN,
    RECEIPT_OUTCOMES,
    RETRACTION_ENUMERATION_DOMAIN,
    SUBJECT_DOMAINS,
    Capture,
    CapturedCertification,
    CapturedCoreference,
    CapturedCorpus,
    CapturedRecord,
    CapturedRetraction,
    CertificationInventory,
    CoreferenceMap,
    DerivationReceipt,
    ProducerSnapshot,
    ReceiptKind,
    ReceiptOutcome,
    address_map,
    address_map_projection,
    belief_input_identity,
    certification_inventory,
    coreference_map,
    derivation_receipts,
    producer_snapshot,
    producers_map_projection,
    retraction_discovery_map,
    retraction_discovery_map_projection,
    retraction_enumeration,
    retraction_enumeration_identity,
    retraction_enumeration_projection,
    subject_identity,
    subject_projection,
)
from science.world.epoch import (
    CURRENT_POINTER,
    DERIVATION_KINDS,
    ENUMERATED_SOURCE_KINDS,
    EPOCH_DOMAIN,
    EPOCH_MEMBERS,
    MEMBER_KEYS,
    RECEIPT_DOMAIN,
    RECEIPT_IDENTITY_KEYS,
    RECEIPT_KEYS,
    RECEIPT_KINDS,
    RETRACTION_RESOLUTIONS,
    DerivationBindings,
    Epoch,
    build_epoch,
    packaging_identity_of,
    receipt_identity,
)
from science.world.read import (
    EDGE_STATES,
    BoundStamp,
    EdgeAnswer,
    Location,
    NotPresent,
    Resolved,
    Unknown,
    coreference_edge,
    current_epoch,
    expand_coreference,
    open_epoch,
    resolve_address,
    validate_receipt,
)
from science.world.registry import (
    AdmissionProvenance,
    AdmissionRecord,
    CorpusManifest,
    CorpusStatus,
    ForkedFrom,
    ForkOf,
    Fresh,
    RegistryView,
    ReplicaOf,
    StatusRecord,
    World,
    WorldConfig,
    admission_digest,
    admission_projection,
    corpus_state_identity,
    load_manifest,
    manifest_bytes,
    manifest_projection,
    provenance_projection,
    status_digest,
    status_projection,
)
from science.world.registry import _lift_json as _lift_json
from science.world.registry import _load_world_mirror as _load_world_mirror
from science.world.registry import _parse_manifest as _parse_manifest
from science.world.registry import _world_mirror_bytes as _world_mirror_bytes
from science.world.rules import (
    FIXTURE_SET_DOMAIN,
    RULE_DOMAIN,
    RuleBinding,
    RuleBundle,
    RuleRemovalReport,
    binding_for,
    fixture_set_identity,
    implementation_identity,
    install_rule_binding,
    member_content_digest,
    parse_rule_document,
    remove_rule_binding,
    rule_document_bytes,
    rule_identity,
    shipped_rule_bundles,
)
from science.world.rules import _HeldRule as _HeldRule
from science.world.rules import _resolve_rule_binding as _resolve_rule_binding

__all__ = [
    "BELIEF_INPUT_KIND",
    "CERTIFICATION_INVENTORY_DOMAIN",
    "COREFERENCE_MAP_DOMAIN",
    "CURRENT_POINTER",
    "DERIVATION_KINDS",
    "EDGE_STATES",
    "ENUMERATED_SOURCE_KINDS",
    "EPOCH_DOMAIN",
    "EPOCH_MEMBERS",
    "FIXTURE_SET_DOMAIN",
    "MEMBER_KEYS",
    "PRODUCER_SNAPSHOT_DOMAIN",
    "RECEIPT_DOMAIN",
    "RECEIPT_IDENTITY_KEYS",
    "RECEIPT_KEYS",
    "RECEIPT_KINDS",
    "RECEIPT_OUTCOMES",
    "RETRACTION_ENUMERATION_DOMAIN",
    "RETRACTION_RESOLUTIONS",
    "RULE_DOMAIN",
    "SUBJECT_DOMAINS",
    "AdmissionProvenance",
    "AdmissionRecord",
    "BoundStamp",
    "Capture",
    "CapturedCertification",
    "CapturedCoreference",
    "CapturedCorpus",
    "CapturedRecord",
    "CapturedRetraction",
    "CertificationInventory",
    "CoreferenceMap",
    "CorpusManifest",
    "CorpusStatus",
    "DerivationBindings",
    "DerivationReceipt",
    "EdgeAnswer",
    "Epoch",
    "ForkOf",
    "ForkedFrom",
    "Fresh",
    "Location",
    "NotPresent",
    "ProducerSnapshot",
    "ReceiptKind",
    "ReceiptOutcome",
    "RegistryView",
    "ReplicaOf",
    "Resolved",
    "RuleBinding",
    "RuleBundle",
    "RuleRemovalReport",
    "StatusRecord",
    "Unknown",
    "World",
    "WorldConfig",
    "address_map",
    "address_map_projection",
    "admission_digest",
    "admission_projection",
    "belief_input_identity",
    "binding_for",
    "build_epoch",
    "certification_inventory",
    "coreference_edge",
    "coreference_map",
    "corpus_state_identity",
    "current_epoch",
    "derivation_receipts",
    "expand_coreference",
    "fixture_set_identity",
    "implementation_identity",
    "install_rule_binding",
    "load_manifest",
    "manifest_bytes",
    "manifest_projection",
    "member_content_digest",
    "open_epoch",
    "packaging_identity_of",
    "parse_rule_document",
    "producer_snapshot",
    "producers_map_projection",
    "provenance_projection",
    "receipt_identity",
    "remove_rule_binding",
    "resolve_address",
    "retraction_discovery_map",
    "retraction_discovery_map_projection",
    "retraction_enumeration",
    "retraction_enumeration_identity",
    "retraction_enumeration_projection",
    "rule_document_bytes",
    "rule_identity",
    "shipped_rule_bundles",
    "status_digest",
    "status_projection",
    "subject_identity",
    "subject_projection",
    "validate_receipt",
]
